### Arithmetic operations

In [1]:
import numpy as np

In [2]:
a=np.arange(1,11)
b=np.arange(21,31)
print("a",a)
print("b",b)

a [ 1  2  3  4  5  6  7  8  9 10]
b [21 22 23 24 25 26 27 28 29 30]


In [3]:
a+b

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [4]:
b-a

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

In [5]:
a*b

array([ 21,  44,  69,  96, 125, 156, 189, 224, 261, 300])

In [6]:
b/a

array([21.        , 11.        ,  7.66666667,  6.        ,  5.        ,
        4.33333333,  3.85714286,  3.5       ,  3.22222222,  3.        ])

In [7]:
a**b

array([          1,     4194304,  -346101685,           0,   167814181,
       -1543503872,    17998615,           0, -1635065239,  1073741824],
      dtype=int32)

In [8]:
a*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [9]:
np.add(a,b)

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [10]:
np.subtract(b,a)

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

In [11]:
np.multiply(a,b)

array([ 21,  44,  69,  96, 125, 156, 189, 224, 261, 300])

In [12]:
np.divide(b,a)

array([21.        , 11.        ,  7.66666667,  6.        ,  5.        ,
        4.33333333,  3.85714286,  3.5       ,  3.22222222,  3.        ])

In [13]:
np.mod(b,a)

array([0, 0, 2, 0, 0, 2, 6, 4, 2, 0], dtype=int32)

In [14]:
np.power(a,b)

array([          1,     4194304,  -346101685,           0,   167814181,
       -1543503872,    17998615,           0, -1635065239,  1073741824],
      dtype=int32)

In [15]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

### Broadcasting

In [16]:
import numpy as np

In [17]:
a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
b=np.arange(1,4)
b

array([1, 2, 3])

In [19]:
a+b

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [20]:
c=np.arange(1,3)
c

array([1, 2])

In [21]:
a+c

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

In [22]:
d=np.arange(24).reshape(2,3,4)
d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [23]:
e=np.arange(4)
e

array([0, 1, 2, 3])

In [24]:
d-e

array([[[ 0,  0,  0,  0],
        [ 4,  4,  4,  4],
        [ 8,  8,  8,  8]],

       [[12, 12, 12, 12],
        [16, 16, 16, 16],
        [20, 20, 20, 20]]])

### Aggregate functions

In [25]:
import numpy as np

In [26]:
first_arr=np.arange(10,110,10)
first_arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [27]:
second_arr=np.arange(10,100,10).reshape(3,3)
second_arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [28]:
third_arr=np.arange(10,110,10).reshape(2,5)
third_arr

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [29]:
first_arr.sum()

550

In [30]:
second_arr.sum()

450

In [31]:
third_arr.sum()

550

In [32]:
second_arr.sum(axis=0)

array([120, 150, 180])

In [33]:
second_arr.sum(axis=1)

array([ 60, 150, 240])

In [34]:
first_arr.prod()

1704722432

In [35]:
second_arr.prod()

-1786839040

In [36]:
third_arr.prod()

1704722432

In [37]:
third_arr.prod(axis=0)

array([ 600, 1400, 2400, 3600, 5000])

In [38]:
np.average(first_arr)

55.0

In [39]:
np.average(second_arr)

50.0

In [40]:
np.average(third_arr)

55.0

In [41]:
np.min(first_arr)

10

In [42]:
np.max(first_arr)

100

In [43]:
np.mean(first_arr)

55.0

In [44]:
np.std(first_arr)

28.722813232690143

### How to get unique items and counts

In [45]:
import numpy as np

In [46]:
first_arr=np.array([1,2,3,4,5,6,1,2,7,2,1,10,7,8])

In [47]:
np.unique(first_arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10])

In [48]:
second_arr=np.array([[1, 1, 2,1] ,[ 3, 1, 2,1] , [1, 1, 2, 1], [ 7, 1, 1, 1]])
second_arr

array([[1, 1, 2, 1],
       [3, 1, 2, 1],
       [1, 1, 2, 1],
       [7, 1, 1, 1]])

In [49]:
np.unique(second_arr)

array([1, 2, 3, 7])

In [50]:
np.unique(second_arr,axis=0)

array([[1, 1, 2, 1],
       [3, 1, 2, 1],
       [7, 1, 1, 1]])

In [51]:
np.unique(second_arr,axis=1)

array([[1, 1, 2],
       [1, 3, 2],
       [1, 1, 2],
       [1, 7, 1]])

In [52]:
np.unique(first_arr,return_index= True)

(array([ 1,  2,  3,  4,  5,  6,  7,  8, 10]),
 array([ 0,  1,  2,  3,  4,  5,  8, 13, 11], dtype=int64))

In [53]:
np.unique(second_arr,return_counts=True)

(array([1, 2, 3, 7]), array([11,  3,  1,  1], dtype=int64))

### Transpose like operations

In [54]:
import numpy as np

In [55]:
first_2dimarr=np.arange(12).reshape((3,4))
first_2dimarr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [56]:
np.transpose(first_2dimarr)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [57]:
second_2dimarr=np.arange(6).reshape(3,2)
second_2dimarr

array([[0, 1],
       [2, 3],
       [4, 5]])

In [58]:
np.transpose(second_2dimarr,(1,0))

array([[0, 2, 4],
       [1, 3, 5]])

In [59]:
first_3dimarr=np.arange(24).reshape(2,3,4)
first_3dimarr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [60]:
np.moveaxis(first_3dimarr,0,-1)

array([[[ 0, 12],
        [ 1, 13],
        [ 2, 14],
        [ 3, 15]],

       [[ 4, 16],
        [ 5, 17],
        [ 6, 18],
        [ 7, 19]],

       [[ 8, 20],
        [ 9, 21],
        [10, 22],
        [11, 23]]])

In [61]:
np.swapaxes(first_3dimarr,0,2)

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

### Reversing an array

In [62]:
import numpy as np

In [63]:
arr_1dim=[10,1,9,2,8,3,7,4,6,5]
arr_1dim

[10, 1, 9, 2, 8, 3, 7, 4, 6, 5]

In [64]:
arr_1dim[::-1]

[5, 6, 4, 7, 3, 8, 2, 9, 1, 10]

In [65]:
np.flip(arr_1dim)

array([ 5,  6,  4,  7,  3,  8,  2,  9,  1, 10])

In [66]:
arr_2dim=np.arange(9).reshape(3,3)
arr_2dim

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [67]:
np.flip(arr_2dim)

array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])

In [68]:
np.flip(arr_2dim,1)

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [69]:
arr_3dim=np.arange(24).reshape(2,3,4)
arr_3dim

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [70]:
np.flip(arr_3dim,1)

array([[[ 8,  9, 10, 11],
        [ 4,  5,  6,  7],
        [ 0,  1,  2,  3]],

       [[20, 21, 22, 23],
        [16, 17, 18, 19],
        [12, 13, 14, 15]]])

In [71]:
np.flip(arr_3dim,2)

array([[[ 3,  2,  1,  0],
        [ 7,  6,  5,  4],
        [11, 10,  9,  8]],

       [[15, 14, 13, 12],
        [19, 18, 17, 16],
        [23, 22, 21, 20]]])