### Adding, removing and sorting elements

In [1]:
import numpy as np

In [2]:
first_arr=np.array([1, 2, 3, 5])
first_arr

array([1, 2, 3, 5])

In [3]:
new_first_arr=np.insert(first_arr,3,4)
new_first_arr

array([1, 2, 3, 4, 5])

In [4]:
second_arr=np.array([1,2,3,4])
second_arr

array([1, 2, 3, 4])

In [5]:
new_second_arr=np.append(second_arr,5)
new_second_arr

array([1, 2, 3, 4, 5])

In [6]:
third_arr=np.array([1,2,3,4,5])
third_arr

array([1, 2, 3, 4, 5])

In [7]:
del_arr=np.delete(third_arr,4)
del_arr

array([1, 2, 3, 4])

In [8]:
integers_arr=np.random.randint(0,20,20)
integers_arr

array([14, 18,  1,  6, 17,  9,  3,  9,  0, 14, 10, 15, 13, 11, 10, 13, 11,
       12, 18, 15])

In [9]:
print(np.sort(integers_arr))

[ 0  1  3  6  9  9 10 10 11 11 12 13 13 14 14 15 15 17 18 18]


In [10]:
integers_2dim_arr=np.array([[3, 2, 5,7, 4], [5, 0, 8,3, 1]])
integers_2dim_arr

array([[3, 2, 5, 7, 4],
       [5, 0, 8, 3, 1]])

In [11]:
print(np.sort(integers_2dim_arr))

[[2 3 4 5 7]
 [0 1 3 5 8]]


In [12]:
colors=np.array(['orange','green','yellow','white','black','pink','blue','red'])
colors

array(['orange', 'green', 'yellow', 'white', 'black', 'pink', 'blue',
       'red'], dtype='<U6')

In [13]:
print(np.sort(colors))

['black' 'blue' 'green' 'orange' 'pink' 'red' 'white' 'yellow']


### Copies and views

In [6]:
import numpy as np

In [7]:
students_ids_number=np.array([1111,1212,1313,1414,1515,1616,1717,1818])
students_ids_number

array([1111, 1212, 1313, 1414, 1515, 1616, 1717, 1818])

In [8]:
students_ids_number_reg=students_ids_number
print("id of students_ids_number",id(students_ids_number))
print("id of students_ids_number_reg",id(students_ids_number_reg))

id of students_ids_number 1793757051664
id of students_ids_number_reg 1793757051664


In [9]:
students_ids_number_reg[1]=2222
print(students_ids_number)
print(students_ids_number_reg)

[1111 2222 1313 1414 1515 1616 1717 1818]
[1111 2222 1313 1414 1515 1616 1717 1818]


In [10]:
students_ids_number_cp=students_ids_number.copy()

In [11]:
print(students_ids_number_cp)

[1111 2222 1313 1414 1515 1616 1717 1818]


In [12]:
print(students_ids_number_cp==students_ids_number)

[ True  True  True  True  True  True  True  True]


In [13]:
print ("id of students_ids_number",id(students_ids_number))
print("id of students_ids_number_cp",id(students_ids_number_cp))

id of students_ids_number 1793757051664
id of students_ids_number_cp 1793751354800


In [14]:
students_ids_number[0]=1000
print ("original: ", students_ids_number)
print("copy: ",students_ids_number_cp)

original:  [1000 2222 1313 1414 1515 1616 1717 1818]
copy:  [1111 2222 1313 1414 1515 1616 1717 1818]


In [15]:
students_ids_number_v=students_ids_number.view()

In [16]:
students_ids_number_v[0]=2000
print("original: ", students_ids_number)
print("view:",students_ids_number_v)

original:  [2000 2222 1313 1414 1515 1616 1717 1818]
view: [2000 2222 1313 1414 1515 1616 1717 1818]


In [17]:
print(students_ids_number_cp.base)
print(students_ids_number_v.base)

None
[2000 2222 1313 1414 1515 1616 1717 1818]


### Reshaping arrays

In [18]:
import numpy as np

In [19]:
first_arr=np.arange(1,13)
first_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [20]:
second_arr=np.reshape(first_arr,(3,4))
second_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
third_arr=np.reshape(first_arr,(6,2))
third_arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [23]:
fifth_arr=np.reshape(first_arr,(3,2,2))
print(fifth_arr)
print("Dimensions of fifth_arr is ",fifth_arr.ndim)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
Dimensions of fifth_arr is  3


In [24]:
sixth_arr=np.array([[1,2],[3,4],[5,6]])
sixth_arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
seventh_arr_flat=np.reshape(sixth_arr,-1)
seventh_arr_flat

array([1, 2, 3, 4, 5, 6])

In [26]:
eighth_arr_flat=sixth_arr.flatten()
print("eighth_arr_flat:",eighth_arr_flat)
ninth_arr_rav=sixth_arr.ravel()
print("ninth_arr_rav:",ninth_arr_rav)

eighth_arr_flat: [1 2 3 4 5 6]
ninth_arr_rav: [1 2 3 4 5 6]


In [27]:
eighth_arr_flat[0]=100

In [28]:
ninth_arr_rav[0]=200

In [29]:
print("eighth_arr_flat:",eighth_arr_flat)
print("ninth_arr_rav:",ninth_arr_rav)
print("sixth_arr:",sixth_arr)

eighth_arr_flat: [100   2   3   4   5   6]
ninth_arr_rav: [200   2   3   4   5   6]
sixth_arr: [[200   2]
 [  3   4]
 [  5   6]]


### Indexing and slicing

In [30]:
import numpy as np

In [31]:
twodim_arr=np.reshape(np.arange(12),(3,4))
twodim_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
twodim_arr[1,1]

5

In [33]:
twodim_arr[1]

array([4, 5, 6, 7])

In [34]:
threedim_arr=np.reshape(np.arange(3*4*5),(3,4,5))
threedim_arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [35]:
threedim_arr[0,2,3]

13

In [36]:
threedim_arr[2,-1,-1]

59

In [37]:
onedim_arr=np.arange(10)
onedim_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
onedim_arr[2:6]

array([2, 3, 4, 5])

In [39]:
onedim_arr[:5]

array([0, 1, 2, 3, 4])

In [40]:
onedim_arr[-3:]

array([7, 8, 9])

In [41]:
onedim_arr[::2]

array([0, 2, 4, 6, 8])

In [42]:
twodim_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
twodim_arr[1:,1:]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [44]:
twodim_arr[1,:]

array([4, 5, 6, 7])

In [45]:
twodim_arr[:,2]

array([ 2,  6, 10])

### Joining and splitting ararys

In [46]:
import numpy as np

In [47]:
first_arr=np.arange(1,11)
second_arr=np.arange(11,21)
print("first_arr",first_arr)
print("second_arr",second_arr)

first_arr [ 1  2  3  4  5  6  7  8  9 10]
second_arr [11 12 13 14 15 16 17 18 19 20]


In [48]:
con_arr=np.concatenate((first_arr,second_arr))
con_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [49]:
third_2darr=np.array([[1,2,3,4,5], [6,7,8,9,10]])
third_2darr


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [50]:
fourth_2darr=np.array([[11,12,13,14,15], [16,17,18,19,20]])
fourth_2darr

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [51]:
con2d_arr = np.concatenate((third_2darr,fourth_2darr),axis=1)
con2d_arr

array([[ 1,  2,  3,  4,  5, 11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10, 16, 17, 18, 19, 20]])

In [52]:
st_arr = np.stack((first_arr,second_arr))
st_arr 

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [53]:
hst_arr=np.hstack((first_arr,second_arr))
hst_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [54]:
vst_arr=np.vstack((first_arr,second_arr))
vst_arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [55]:
fifth_arr=np.arange(1,13)
fifth_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [56]:
sp_arr=np.array_split(fifth_arr,4)
sp_arr

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]

In [57]:
print(sp_arr[1])

[4 5 6]


In [58]:
sp_arr=np.array_split(fifth_arr,8)
sp_arr

[array([1, 2]),
 array([3, 4]),
 array([5, 6]),
 array([7, 8]),
 array([9]),
 array([10]),
 array([11]),
 array([12])]

In [59]:
np.hsplit(third_2darr,5)


[array([[1],
        [6]]),
 array([[2],
        [7]]),
 array([[3],
        [8]]),
 array([[4],
        [9]]),
 array([[ 5],
        [10]])]

In [61]:
vs_arr=np.vsplit(third_2darr,2)
vs_arr

[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]])]