### Array types and conversions between types

In [1]:
import numpy as np

In [2]:
integers=np.array([10,20,30,40,50])

In [3]:
integers

array([10, 20, 30, 40, 50])

In [4]:
integers[0]

10

In [5]:
integers[0]=20
integers

array([20, 20, 30, 40, 50])

In [6]:
integers[0]=21.5
integers

array([21, 20, 30, 40, 50])

In [7]:
integers.dtype

dtype('int32')

In [8]:
smallerIntegers=np.array(integers,dtype=np.int8)

In [9]:
smallerIntegers

array([21, 20, 30, 40, 50], dtype=int8)

In [10]:
integers.nbytes

20

In [11]:
smallerIntegers.nbytes

5

In [12]:
overflow = np.array([127,128,129], dtype = np.int8)
overflow

array([ 127, -128, -127], dtype=int8)

In [13]:
floats=np.array([1.2,2.3,3.4,5.1,8.3])

In [14]:
floats

array([1.2, 2.3, 3.4, 5.1, 8.3])

In [15]:
floats.dtype

dtype('float64')

### Multidimensional arrays

In [1]:
import numpy as np

In [2]:
nums=np.array([[1,2,3,4,5],[6,7,8,9,10]])
nums

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [3]:
nums[0,0]

1

In [4]:
nums[1,4]

10

In [5]:
nums.ndim

2

In [6]:
multi_arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [7]:
multi_arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [8]:
multi_arr[1,0,2]

9

### Creating arrays from Lists and other Python structures

In [1]:
import numpy as np

In [2]:
first_list=[1,2,3,4,5,6,7,8,9,10]

In [3]:
first_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [4]:
first_array=np.array(first_list)

In [5]:
first_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
second_list=[1,2,3,-1.23,50,128000.56,4.56]

In [7]:
second_array=np.array(second_list)

In [8]:
second_array

array([ 1.0000000e+00,  2.0000000e+00,  3.0000000e+00, -1.2300000e+00,
        5.0000000e+01,  1.2800056e+05,  4.5600000e+00])

In [9]:
second_array.dtype

dtype('float64')

In [10]:
third_list=['Ann',111111,'Peter',111112,'Susan',111113,'John',111114]


In [11]:
third_array=np.array(third_list)

In [12]:
third_array

array(['Ann', '111111', 'Peter', '111112', 'Susan', '111113', 'John',
       '111114'], dtype='<U11')

In [13]:
first_tuple=(5, 10, 15, 20, 25, 30)


In [14]:
array_from_tuple=np.array(first_tuple)

In [15]:
array_from_tuple

array([ 5, 10, 15, 20, 25, 30])

In [16]:
array_from_tuple.dtype

dtype('int32')

In [17]:
multi_dim_list=[[[0,1,2], [3,4,5]], [[6,7,8],[9,10,11]]] 

In [18]:
arr_from_multi_dim_list=np.array(multi_dim_list)

In [19]:
arr_from_multi_dim_list

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

### Intrisic NumPy array creation

In [1]:
import numpy as np

In [2]:
integers_array=np.arange(10)
integers_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
integers_second_array=np.arange(100,130)
integers_second_array

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129])

In [4]:
integers_third_array=np.arange(100,151,2)
integers_third_array

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
       126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150])

In [5]:
first_floats_arr=np.linspace(10,20)
first_floats_arr

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [6]:
second_floats_arr=np.linspace(10,20,5)
second_floats_arr

array([10. , 12.5, 15. , 17.5, 20. ])

In [7]:
first_rand_arr=np.random.rand(10)
first_rand_arr

array([0.94375144, 0.66682097, 0.00099597, 0.77613137, 0.83724168,
       0.37279952, 0.03343288, 0.60980425, 0.67993977, 0.86965017])

In [8]:
second_rand_arr=np.random.rand(4,4)
second_rand_arr

array([[0.55394419, 0.31174235, 0.23399197, 0.64604697],
       [0.23339458, 0.86335413, 0.76012283, 0.82150023],
       [0.77556772, 0.85961781, 0.61465424, 0.81318086],
       [0.82960585, 0.50000401, 0.36709591, 0.21131456]])

In [9]:
third_rand_arr=np.random.randint(0,100,20)
third_rand_arr

array([85, 46, 62, 26, 10, 98, 88,  5,  9, 41, 32, 27, 27, 28,  0, 21, 18,
       44, 54, 97])

### Creating arrays filled with constant values

In [1]:
import numpy as np

In [2]:
first_z_array=np.zeros(5)
first_z_array

array([0., 0., 0., 0., 0.])

In [3]:
second_z_array=np.zeros((4,5))
second_z_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
first_ones_array=np.ones(6)
first_ones_array

array([1., 1., 1., 1., 1., 1.])

In [5]:
second_ones_array=np.ones((7,8))
second_ones_array

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [6]:
third_ones_array=np.ones((4,5),dtype=int)
third_ones_array

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [7]:
first_fill_array=np.empty(10,dtype=int)
first_fill_array.fill(12)
first_fill_array

array([12, 12, 12, 12, 12, 12, 12, 12, 12, 12])

In [8]:
first_full_array=np.full(5,10)
first_full_array

array([10, 10, 10, 10, 10])

In [9]:
second_full_array=np.full((4,5),8)
second_full_array

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

###  Finding the shape and size of an array

In [1]:
import numpy as np

In [2]:
first_arr=np.arange(20)
first_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [3]:
second_arr=np.linspace((1,2),(10,20),10)
second_arr

array([[ 1.,  2.],
       [ 2.,  4.],
       [ 3.,  6.],
       [ 4.,  8.],
       [ 5., 10.],
       [ 6., 12.],
       [ 7., 14.],
       [ 8., 16.],
       [ 9., 18.],
       [10., 20.]])

In [4]:
third_arr=np.full((2,2,2),10)
third_arr

array([[[10, 10],
        [10, 10]],

       [[10, 10],
        [10, 10]]])

In [5]:
np.shape(first_arr)

(20,)

In [6]:
np.shape(second_arr)

(10, 2)

In [7]:
np.shape(third_arr)

(2, 2, 2)

In [8]:
np.size(first_arr)

20

In [9]:
np.size(second_arr)

20

In [10]:
np.size(third_arr)

8